/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    'Auth.page': typeof import('./src/components/auth/auth.page.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    ConfigMenu: typeof import('./src/components/config/config-menu.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    'Home.page': typeof import('./src/components/home.page.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    'Login.page': typeof import('./src/components/auth/login.page.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Panel: typeof import('primevue/panel')['default']
    'PoDetail.page': typeof import('./src/components/document/po-detail.page.vue')['default']
    'PrDetail.page': typeof import('./src/components/document/pr-detail.page.vue')['default']
    'Register.page': typeof import('./src/components/auth/register.page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    'User.page': typeof import('./src/components/config/user.page.vue')['default']
    'Workflow.page': typeof import('./src/components/config/workflow.page.vue')['default']
    'WorkflowRule.page': typeof import('./src/components/config/workflow-rule.page.vue')['default']
  }
}
